### ISSUE TITLE
Livro disponível online!

### ISSUE THREAD

**Issue by aristidesneto** [caiodelgadonew/docker-dca#2]
Caio, você acha interessante publicar esse conteúdo também online usando por exemplo o Honkit?

Particularmente acho bacana estar disponível online além de estar em PDF seu livro.

Se achar interessante posso contribuir migrando para essa ferramenta.

Vlw

**Comment by aristidesneto** [comment]
Abri a issue no repo errado... desculpe!

**Comment by caiodelgadonew** [comment]
Opa, sem problemas, vou fechar aqui!
